INSERT INTO genre_table (genre_name) VALUES 
('Action'),
('Adventure'),
('Comedy'),
('Drama'),
('Fantasy'),
('Horror'),
('Mystery'),
('Romance'),
('Science Fiction'),
('Thriller'),
('Animation'),
('Documentary'),
('Family'),
('Musical'),
('War'),
('Western'),
('Crime'),
('Historical'),
('Biographical'),
('Superhero'),
('Spy'),
('Sports'),
('Cooking'),
('Fashion'),
('Travel'),
('Business'),
('News'),
('Reality Show'),
('Talk Show'),
('Variety Show');
