INSERT INTO program_table (program_title, program_description)
VALUES
    ('News Hour', 'A one-hour program featuring the latest news from around the world.'),
    ('Morning Coffee', 'A morning show to start your day off right!'),
    ('Documentary Series: The Natural World', 'A stunning exploration of the natural world.'),
    ('Cooking with Julia', 'Join Julia as she takes you through her favorite recipes.'),
    ('Sports Roundup', 'All the latest scores, highlights, and analysis.'),
    ('Movie Night: Classic Films', 'Join us for a classic movie every week.'),
    ('The Comedy Hour', 'Laugh out loud with our hilarious comedians!'),
    ('The Science Hour', 'Explore the wonders of science with our experts.'),
    ('The Art of Painting', 'Join our host as they teach you the art of painting.'),
    ('Music Showcase', 'Featuring the hottest new artists and classic hits.'),
    ('Drama Series: The Secret', 'A gripping drama about love, betrayal, and intrigue.'),
    ('Travel the World', 'Explore new destinations and cultures with us.'),
    ('The Business Report', 'Stay informed on the latest business news and trends.'),
    ('Fashion Forward', 'All the latest trends and styles from the world of fashion.'),
    ('The Great Outdoors', 'Discover the beauty and adventure of the great outdoors.'),
    ('True Crime Stories', 'Real-life stories of crime and justice.'),
    ('Gaming Live', 'Join us for live gameplay and commentary.'),
    ('The Science of Cooking', 'Explore the chemistry and physics of cooking.'),
    ('Music Legends', 'A tribute to the greatest musicians of all time.'),
    ('The World of Sports', 'Get an in-depth look at the world of sports.'),
    ('The Politics Hour', 'Debate and discussion on the latest political issues.'),
    ('Movie Night: Action Movies', 'Join us for an action-packed movie every week.'),
    ('The Health Report', 'Stay up-to-date on the latest health news and trends.'),
    ('The Art of Photography', 'Learn the art of photography with our expert host.'),
    ('Music Videos', 'Featuring the latest music videos and exclusive performances.'),
    ('Drama Series: The Intruder', 'A thrilling drama about the dark side of human nature.'),
    ('The Food Show', 'Join us for a delicious journey through the world of food.'),
    ('History Uncovered', 'Explore the mysteries and secrets of history.'),
    ('The Environment Report', 'Stay informed on the latest environmental news and issues.'),
    ('Fashion Icons', 'A tribute to the most iconic fashion designers and trends.'),
    ('Sports Legends', 'A tribute to the greatest athletes of all time.');
