INSERT INTO season_table (season_number, program_id) 
SELECT ROUND(RAND() * 10) + 1, program_id 
FROM program_table 
CROSS JOIN (SELECT 0 AS n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) AS digit
ORDER BY RAND() 
LIMIT 30;