version: '3.1'

services:
  mysql:
    build: .
    restart: always
    working_dir: /mysql-study
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - data-volumes:/var/lib/mysql
      - ./test_db:/test_db
      - ./mysql-study:/mysql-study

volumes:
  data-volumes:
