version: '3.7'
services:
  app:
    build: .
    image: ubuntu-image
    tty: true
    stdin_open: true
    volumes:
      - .:/linux-study
    environment:
      - PASSPHRASE_ENV_VAR=${HOST_PASSPHRASE_ENV_VAR}